{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units1", "default": null, "conditions": [], "min_value": 10, "max_value": 100, "step": 10, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 10, "max_value": 100, "step": 10, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "optimizer", "default": "adam", "conditions": [], "values": ["adam", "sgd", "rmsprop"], "ordered": false}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 10, "max_value": 100, "step": 10, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_4", "default": null, "conditions": [], "min_value": 10, "max_value": 100, "step": 10, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_5", "default": null, "conditions": [], "min_value": 10, "max_value": 100, "step": 10, "sampling": "linear"}}], "values": {"units1": 40, "num_layers": 4, "units_2": 70, "optimizer": "adam", "tuner/epochs": 2, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0, "units_3": 10, "units_4": 10, "units_5": 10}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/workspaces/ANN-Regression/venv/lib/python3.9/site-packages/keras/src/trainers/data_adapters/data_adapter_utils.py\", line 114, in check_data_cardinality\n    raise ValueError(msg)\nValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 1158\n'y' sizes: 856\n\n"}